### PR TITLE
verify that we're running from the root of a project

### LINKED ISSUE #96: fast fail when run from a directory that is not a project root
`No pubspec.yaml file found. The flutter command should be run from the root of a project.`

### LINKED ISSUE #107: early calls to `exit()`
There are some early calls to `exit(int)`. We should probably throw at these locations, or pass back an exit status code through the `Future<int> run()` methods.

https://github.com/flutter/tools/blob/master/lib/src/commands/flutter_command_runner.dart#L120

### PR DESCRIPTION
**Pull request by devoncarew**
- change some early calls to `exit()` to throw instead (fix #107)
- make many commands that require being run in a project root fast fail if they can't find a pubspec (fix #96)
- change some places where we're logging issues to instead write to stderr
- fix an analysis issue in the sample app we create

### CODE REVIEW

**Comment by devoncarew** [comment]
@abarth, @Hixie 

There's a fix in here to the sample app template (the int ==> enum change). We should land that fix soon and re-publish this package - the current sample we create doesn't work out of the box.

File: lib/src/commands/flutter_command.dart [hunk 1]
```diff
@@ -40,6 +44,20 @@ abstract class FlutterCommand extends Command {
...
+        stderr.writeln('No pubspec.yaml file found. '
+            'This command should be run from the root of a project.');
+        return 1;
+      }
+    }
+
+    return projectRun();
+  }
+
+  Future<int> projectRun();
```
Comment (abarth) [inline lib/src/commands/flutter_command.dart]: runInProject ?

File: lib/src/commands/flutter_command_runner.dart [hunk 2]
```diff
@@ -116,8 +116,8 @@ class FlutterCommandRunner extends CommandRunner {
         else
           message += '\nDid you run this command from the same directory as your pubspec.yaml file?';
       }
-      _logging.severe(message);
-      exit(2);
+      stderr.writeln(message);
+      throw 2;
```
Comment (abarth) [inline lib/src/commands/flutter_command_runner.dart]: Can we through an exception that wraps the integer?  For example, a ProcessExit exception?  Throwing an integer seems pretty raw...

File: lib/src/commands/init.dart [hunk 3]
```diff
@@ -161,7 +161,7 @@ class FlutterDemo extends StatelessComponent {
       floatingActionButton: new FloatingActionButton(
         child: new Icon(
           type: 'content/add',
-          size: 24
+          size: IconSize.s24
```
Comment (abarth) [inline lib/src/commands/init.dart]: I'd just remove this argument.  It's the default value.

File: lib/src/commands/flutter_command_runner.dart (hunk 2 above)
Comment (devoncarew) [inline lib/src/commands/flutter_command_runner.dart]: Yup, added a `ProcessExit` class

File: lib/src/commands/init.dart (hunk 3 above)
Comment (devoncarew) [inline lib/src/commands/init.dart]: done

File: lib/src/commands/flutter_command.dart (hunk 1 above)
Comment (devoncarew) [inline lib/src/commands/flutter_command.dart]: changed

File: lib/executable.dart [hunk 4]
```diff
@@ -58,6 +59,16 @@ Future main(List<String> args) async {
       exit(result);
   } on UsageException catch (e) {
     stderr.writeln(e);
-    exit(4);
+    // Args error exit code.
+    exit(64);
+  } catch (e, st) {
```
Comment (abarth) [inline lib/executable.dart]: s/st/stack/

**Comment by abarth** [comment]
LGTM

File: lib/executable.dart (hunk 4 above)
Comment (devoncarew) [inline lib/executable.dart]: done

File: pubspec.yaml [hunk 5]
```diff
@@ -19,7 +19,7 @@ dependencies:
   shelf_route: ^0.13.4
   shelf_static: ^0.2.3
   shelf: ^0.6.2
-  test: ^0.12.5
+  test: 0.12.4+9
```
Comment (devoncarew) [inline pubspec.yaml]: oops, unintentional; will revert
